final List<String> departments = [
  "Accounting",
  "Agriculture",
  "Anthropology",
  "Architecture",
  "Automobile Engineering",
  "Biology",
  "Biomedical Sciences",
  "Botany",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Commerce",
  "Computer Engineering",
  "Computer Science",
  "Criminal Law",
  "Dentistry",
  "Design",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronics and Telecommunication",
  "English Literature",
  "Environmental Science",
  "Finance",
  "Fine Arts",
  "Geography",
  "History",
  "Hospitality and Tourism Management",
  "Human Resource Management",
  "Information Science (LIS)",
  "International Business",
  "International Law",
  "Journalism and Mass Communication",
  "Languages",
  "Law",
  "Library and Information Science",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Physiotherapy",
  "Political Science",
  "Psychology",
  "Public Health",
  "Social Work",
  "Sociology",
  "Statistics",
  "Veterinary Science",
  "Zoology"
];
