// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgzI_VkQzoJd-TkOsRYMDWdOQf-ylXiHE',
    appId: '1:597336221623:web:3abed58f99e3d7d86baa32',
    messagingSenderId: '597336221623',
    projectId: 'smart-attendance-proximity',
    authDomain: 'smart-attendance-proximity.firebaseapp.com',
    storageBucket: 'smart-attendance-proximity.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJn4fNrLb2_dFbxT8ZfXWs9rg6iy6hY4',
    appId: '1:597336221623:android:9a2794cc1f89afc56baa32',
    messagingSenderId: '597336221623',
    projectId: 'smart-attendance-proximity',
    storageBucket: 'smart-attendance-proximity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqClY98GuCGGpo73xZemndKVKTxxBf9I',
    appId: '1:597336221623:ios:9d33d0ba70a7ff6e6baa32',
    messagingSenderId: '597336221623',
    projectId: 'smart-attendance-proximity',
    storageBucket: 'smart-attendance-proximity.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceBluetooth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqClY98GuCGGpo73xZemndKVKTxxBf9I',
    appId: '1:597336221623:ios:9d33d0ba70a7ff6e6baa32',
    messagingSenderId: '597336221623',
    projectId: 'smart-attendance-proximity',
    storageBucket: 'smart-attendance-proximity.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceBluetooth',
  );
}
